name: 'NextKiwi: Rebase on top of chromium branch'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setting-up GitHub username
        run: |
          git config --global user.email "github@actions"
          git config --global user.name "NextKiwi bot"

      - name: Fetching latest from repository
        run: git fetch origin

      - name: Switching to Chromium base
        run: git checkout origin/chromium

      - name: Rebasing nextkiwi on top of Chromium
        run: git rebase origin/nextkiwi --committer-date-is-author-date

      - name: Pushing updated branch
        run: git push origin HEAD:nextkiwi --force