name: 'Chromium: Update files from upstream'

on:
  workflow_dispatch:
    inputs:
      NEW_CHROMIUM_MAJOR:
        description: 'Major version of Chromium'
        required: true
        default: '140'
      NEW_CHROMIUM_MINOR:
        description: 'Minor version of Chromium'
        required: true
        default: '0'
      NEW_CHROMIUM_BUILD:
        description: 'Build version of Chromium'
        required: true
        default: '0'
      NEW_CHROMIUM_PATCH:
        description: 'Patch version of Chromium'
        required: true
        default: '0'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Disable Git auto-packing
        run: git config --global gc.auto 0
        
      - name: Setting-up GitHub username
        run: |
          git config --global user.email "github@actions"
          git config --global user.name "NextKiwi bot"
          
      - name: Disabling Git pager
        run: git config --global core.pager 'cat'

      - name: Loading current settings from CHROMIUM_VERSION
        run: |
          if [ -f "CHROMIUM_VERSION" ]; then
            source CHROMIUM_VERSION;
            export $(cut -d= -f1 CHROMIUM_VERSION | grep -vF '#');
            env | grep -F CHROMIUM_ >> $GITHUB_ENV
          fi;

      - name: Listing source files
        run: find . -type f -not -path './.git/*' | sed 's#\./#/#g' | grep -vFi '.gitignore' > /tmp/source_files.txt
        
      - name: Checking out Chromium
        run: |
          if [ ! -d /tmp/chromium_new/.git ]; then
            git clone --filter=tree:0 --no-checkout https://chromium.googlesource.com/chromium/src.git /tmp/chromium_new
          else
            cd /tmp/chromium_new && git fetch origin
          fi

      - name: Limiting the list of files to checkout
        run: cd /tmp/chromium_new && cat /tmp/source_files.txt | git sparse-checkout set --stdin

      - name: Switching Chromium to new version
        run: cd /tmp/chromium_new && git read-tree -mu ${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}

      - name: Copying files to local branch
        run: rsync -avz --progress --exclude=".git" /tmp/chromium_new/* .

      - name: Adding files
        run: git add .

      - name: Updating CHROMIUM_VERSION file
        run: |
          echo "CHROMIUM_MAJOR=${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}" > CHROMIUM_VERSION
          echo "CHROMIUM_MINOR=${{ github.event.inputs.NEW_CHROMIUM_MINOR }}" >> CHROMIUM_VERSION
          echo "CHROMIUM_BUILD=${{ github.event.inputs.NEW_CHROMIUM_BUILD }}" >> CHROMIUM_VERSION
          echo "CHROMIUM_PATCH=${{ github.event.inputs.NEW_CHROMIUM_PATCH }}" >> CHROMIUM_VERSION

      - name: Creating pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chromium_${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}
          base: nextkiwi
          delete-branch: true
          signoff: true
          title: "Update Chromium to ${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}"
          commit-message: "[Chromium] Update to ${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}"
          body: |
            Chromium version update: ${{ env.CHROMIUM_MAJOR }}.${{ env.CHROMIUM_MINOR }}.${{ env.CHROMIUM_BUILD }}.${{ env.CHROMIUM_PATCH }} → ${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}
            
            Initiated by ${{ github.actor }}